# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               'Chihab Otmani'
tagline:             ''
description:         'An Object Oriented mind now thinking Functional.'
url:                 http://chihab.github.io
baseurl:             'http://chihab.github.io'
paginate:            5

# About/contact
author:
  name:              Chihab Otmani
  url:               https://www.linkedin.com/in/chihab
  email:             chihab@gmail.com

# Custom vars
version:             1.0.0
