# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            'Chihab Otmani'
tagline:          ''
description:      'An Object Oriented mind now thinking Functional.'
url:              http://chihab.github.io
baseurl:          /

author:
  name:              Chihab Otmani
  url:               https://www.linkedin.com/in/chihab
  email:             chihab@gmail.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/chihab

gems: [jekyll-paginate, jekyll-gist]
